spring.datasource.url=jdbc:mysql://localhost:3306/college_portal
spring.datasource.username=root
spring.datasource.password=PVPSIT@123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080